angular.module('myApp', ['ngRoute',
                        'AppRoutes',
                         'UserCtrl',
                         'SearchCtrl',
                         'spCtrl',
                         'countCTRL',
                         'viewCIN',
                         'viewCONC',
                         'viewER',
                         'viewF',
                         'viewK',
                         'viewM',
                         'viewR',
                         'viewTH',
                         'viewTR',
                         'CinemaReviewsCtrl',
                         'ConcertReviewsCtrl',
                         'EscapeRoomReviewsCtrl',
                         'FightReviewsCtrl',
                         'KoraReviewsCtrl',
                         'MalahyReviewsCtrl',
                         'RaceReviewsCtrl',
                          'TheatreReviewsCtrl',
                         'TrampolineReviewsCtrl',
                        'SignInCtrl',
                        'SignUpCtrl',
                        'SignOutCtrl','FilterCtrl','filter','user','business','SC','AM','TM','TMP','PostOffer','AC','cinema','concert','escapeRoom','fight','kora','malahy','race','theatre','trampoline']);


